### ISSUE TITLE
DynamoDB table config yaml file (help/question)

### ISSUE THREAD

**Issue by kuronaru** [miguelgrinberg/slam#8]
i'm pretty new on using Flask and i encountered this error.
is it related to the lambda function generated by slam or what?

```
HTTP/1.1 502 Bad Gateway
Connection: keep-alive
Content-Length: 36
Content-Type: application/json
Date: Mon, 22 May 2017 08:12:29 GMT
Via: 1.1 ae7118021d10200685649b5e21d1bf9f.cloudfront.net (CloudFront)
X-Amz-Cf-Id: AbdRCe-NRfOJRACxZGUvLelG002kNugyfvgBhfBl5OFchVcOM1bSBQ==
X-Cache: Error from cloudfront
x-amzn-RequestId: 65d6c489-3ec6-11e7-97bc-e962a70966bf

{
    "message": "Internal server error"
}
```

**Comment by kuronaru** [comment]
it seems that it is related to dynamodb_tables that i misconfigured

**Comment by kuronaru** [comment]
i have this database model using PynamoDB:

```
class UserEmailViewIndex(GlobalSecondaryIndex):
    class Meta:
        index_name = "email_view_index"
        read_capacity_units = 1
        write_capacity_units = 1
        projection = AllProjection()
    email = UnicodeAttribute(hash_key=True)

class User(Model):
    class Meta:
        table_name = os.environ.get('STAGE') + '.Users'
        region = boto3.Session().region_name
        host = 'http://localhost:8000' \
            if not os.environ.get('LAMBDA_TASK_ROOT') else None
    id = UnicodeAttribute(hash_key=True)
    first_name = UnicodeAttribute()
    last_name = UnicodeAttribute()
    email = UnicodeAttribute()
    password = UnicodeAttribute()
    address = MapAttribute()
    gender = UnicodeAttribute()
    mobile_number = UnicodeAttribute()
    birthday = UnicodeAttribute()
    accepted_terms = MapAttribute()
    email_view_index = UserEmailViewIndex()
    date_created = UTCDateTimeAttribute()
    date_updated = UTCDateTimeAttribute()
    last_login = UTCDateTimeAttribute()


class PurchaseUserViewIndex(GlobalSecondaryIndex):
    class Meta:
        index_name = "user_view_index"
        read_capacity_units = 1
        write_capacity_units = 1
        projection = AllProjection()
    user_id = UnicodeAttribute(hash_key=True)

class Purchase(Model):
    class Meta:
        table_name = os.environ.get('STAGE') +'.Purchases'
        region = boto3.Session().region_name
        host = 'http://localhost:8000' \
            if not os.environ.get('LAMBDA_TASK_ROOT') else None
    id = UnicodeAttribute(hash_key=True)
    user_id = UnicodeAttribute()
    amount = NumberAttribute()
    store_name = UnicodeAttribute()
    card_number = UnicodeAttribute()
    transaction_date = UnicodeAttribute()
    transaction_type = UnicodeAttribute()
    num_of_entries = NumberAttribute(default=0)
    campaign = MapAttribute()
    user_view_index = PurchaseUserViewIndex()
    date_created = UTCDateTimeAttribute()
```

and i have this in `slam.yaml` file:

```
dynamodb_tables:
  Purchases:
    attributes:
      id: "S"
      user_id: "S"
    key: "id"
    read_throughput: 1
    write_throughput: 1
    global_secondary_indexes:
      user_view_index:
        key: ["user_id"]
        project: "all"
        read_throughput: 1
        write_throughput: 1

  Users:
    attributes:
      id: "S"
      email: "S"
    key: "id"
    read_throughput: 1
    write_throughput: 1
    global_secondary_indexes:
      email_view_index:
        key: ["email"]
        project: "all"
        read_throughput: 1
        write_throughput: 1
```

and i have this error in AWS CloudFormation: `Value of property GlobalSecondaryIndexes must be of type List`


can you check if my config is correct? thanks

**Comment by miguelgrinberg** [comment]
@kuronaru This was a bug on my side. Please upgrade slam to latest release and retry.

**Comment by kuronaru** [comment]
still no luck, i can't deploy my project because of the dynamo_table config in yaml

**Comment by kuronaru** [comment]
i think there's something wrong with the projection.
i checked the template generated by `slam template` and the 
`"Projection": {
      "ProjectionType": "KEYS_ONLY"
                        },`

**Comment by miguelgrinberg** [comment]
I will run a complete example later when I have a bit of time. Do you know what is the error with the projection portion of the cloudformation template?

**Comment by kuronaru** [comment]
i was able to deploy now after re-updating all the libraries in requirements.txt and i checked the template again and the `ProjectionType` is still set as `KEYS_ONLY` though i set it as `all`

i checked the logs by `slam logs --tail`

```
$ slam logs --tail
May 24 13:48:50 START RequestId: a7cf6548-4044-11e7-9534-17871a9c07ee Version: $LATEST
May 24 13:48:58 Failed to query items: An error occurred (AccessDeniedException) on request (PN8ILQLJ53EEIS2BQ9TNIBDKJNVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (dev.Users) when calling the Query operation: : QueryError
```

is the template generating the policies right or i need to configure in the AWS console for this? 

i also noticed that in API Gateway Resources at AWS Console it looks like the screenshot unlike using serverless:
![screenshot_2017-05-24_14-01-47](https://cloud.githubusercontent.com/assets/5925092/26388909/aa30a46e-4089-11e7-9fdc-76c1d4e8e8a6.png)

is it normal to look like that?

please bear with me

**Comment by miguelgrinberg** [comment]
The project problem ended up being another bug. The documentation indicated you should use `project`, but in the code, I was using `projection`. I updated the code to match the documentation.

The API Gateway configuration is correct. I plan to eventually add support for authorization at the gateway level, but at this point, authorization can only be provided in the WSGI application.

**Comment by kuronaru** [comment]
thanks for the response.
any idea what causes the QueryError like what in the `slam logs`?

**Comment by miguelgrinberg** [comment]
@kuronaru is that line in the log generated by your application? I'm not familiar with that log format. In any case, there is an `AccessDeniedException`. It would be useful if you let that exception bubble up, so that the log will show a complete error message and a stack trace.

**Comment by psaks** [comment]
I had the same issue, and it turned out to be a issue with the yml file. In the following section you need to add;

```
iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: 
        - "arn:aws:dynamodb:{YOUR-TABLE}/index/*"
```

In summary, you need to add specific permissions to the index to be able to query the GSI.
